version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src       # ホストの src をコンテナにマウント
      - /app/node_modules    # node_modules はコンテナ側を使う
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
